#!/bin/bash
# Personal setup script for my laptop computer
# ~Dragonwolf
# Version 1.1

if [[ $EUID -ne 0 ]]; then
   	echo "This script must be run as root type: sudo ./installscript" 
   	exit 1
else
	#Fetching Needed Files
		echo "Fetching needed files"
		cd /tmp || return
		wget  https://github.com/Dreamingwolf/Setup-Scripts/raw/master/Dragonwing_hosts

	#Updating Sudoers File to Add NOPASSWD to User
		echo "Adding NOPASSWD to sudoers file"
		echo "david ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers

	#Update hosts file
		echo "Updating the hosts file"
		sudo mv -f ./Dragonwing_hosts /etc/hosts
		
fi
	