#!/bin/bash
# Personal App Install File
# ver. 0.1

if [[ $EUID -ne 0 ]]; then
   	echo "This script must be run as root type: sudo ./arco_apps" 
   	exit 1
else
	while ! [ -x "$(command -v yay)" ]; do
		echo "yay command isn't installed, so I will install it now."
		wget https://aur.archlinux.org/cgit/aur.git/snapshot/yay-bin.tar.gz
        sudo tar -xvf ./yay-bin.tar.gz
        cd yay-bin || return
        makepkg -i
        cd .. || return
        sudo rm -fR ./yay-bin
    done
    if [ -x "$(command -v firefox)" ]; then
    	sudo pacman -Rn --cascade firefox
    fi
    if [ -x "$(command -v chromium)" ]; then
    	sudo pacman -Rn --cascade chromium
    fi
    if [ -x "$(command -v dropbox)" ]; then
    	sudo pacman -Rn --cascade dropbox
    fi
    if [ -x "$(command -v spotify)" ]; then
    	sudo pacman -Rn --cascade spotify
    fi
    if [ -x "$(command -v vivaldi)" ]; then
    	sudo pacman -Rn --cascade vivaldi-codecs-ffmpeg-extra-bin vivaldi
    fi
    if [ -d "/home/david/.home/WinFonts" ]
        then
            sudo mkdir /usr/share/fonts/WindowsFonts
            sudo cp -fR /home/david/.home/WinFonts /usr/share/fonts/WindowsFonts
            sudo chmod 755 /usr/share/fonts/WindowsFonts/*
            sudo fc-cache -f
    fi
    yay --editmenu --nodiffmenu --save
    # Overgrive prep
        yay -S --needed --noconfirm libnotify python python2-pyinotify python2-pip python2-gobject libappindicator-gtk3
        sudo pip2.7 install --upgrade google-api-python-client
        sudo pip2.7 install --upgrade oauth2client
    yay -S --needed --noconfirm linux-headers nvidia-dkms nvidia-settings nvidia-utils lib32-nvidia-utils pass ruby xorg-server-devel opencl-nvidia qrencode tk firefox-nightly thunderbird-nightly
    yay -S --needed --noconfirm p7zip p7zip-gui wimlib overgrive qtwebflix-git zoom discord telegram-desktop-systemqt-notoemoji smplayer smplayer-themes smplayer-skins smtube youtube-dl mplayer
    yay -S --needed --noconfirm python-pyqt5 drkonqi breeze-icons gst-libav flite kwalletmanager kio-extras kdoctools knetattach kirigami2 qt5-tools catdoc kdeconnect sdl_image sox movit
    yay -S --needed --noconfirm dvdauthor dvgrab recordmydesktop simplescreenrecorder xine-ui xsane-gimp dvd+rw-tools vcdimager emovix cdrdao transcode openmp dmenu pam-gnupg-git luajit
    yay -S --needed --noconfirm python-opengl qt5-xmlpatterns qt5-serialport qt5-websockets qt5-connectivity qt5-networkauth kimageformats khtml libappimage clang botan kde-cli-tools opusfile
    yay -S --needed --noconfirm gnome-boxes libvirt virtualbox virtualbox-guest-dkms virtualbox-guest-iso virtualbox-guest-utils virtualbox-host-dkms sublime-text sublime-merge
    yay -S --needed --noconfirm steam steam-fonts pidgin-opensteamworks linux-steam-integration sc-controller-git steamcurses-git proton-git python2-steamodd protonfixes-git gimp obs-studio
    yay -S --needed --noconfirm lib32-mesa-vdpau lib32-libpulse lib32-jack lib32-libsamplerate lib32-speex lib32-giflib lib32-libldap lib32-gnutls lib32-mpg123 lib32-openal lib32-v4l-utils
    yay -S --needed --noconfirm lib32-libxcomposite lib32-libxinerama opencl-icd-loader lib32-opencl-icd-loader lib32-libxslt lib32-gst-plugins-base-libs python2-pygments python2-rdflib
    yay -S --needed --noconfirm lib32-sdl lib32-fluidsynth lib32-opencl-driver lutris hexchat shotwell audacity reaper-bin guvcview jdk-openjdk java-rhino catfish grub-customizer
    yay -S --needed --noconfirm fusesmb samba cifs-utils exfat-utils ntfs-3g-fuse engrampa arj lzip unrar unace darktable gwenview inkscape okular skanlite hplip xsane xsane-gimp
    yay -S --needed --noconfirm kipi-plugins kamera kdegraphics-mobipocket chmlib calligra libmediawiki libkvkontakte libwpg libwps libvisio libetonyek pstoedit openjpeg libgit2
    yay -S --needed --noconfirm openshot simplescreenrecorder libreoffice-fresh libmythes beanshell shellcheck unixodbc postgresql-libs coin-or-mp wqy-zenhei
    sudo glib-compile-schemas /usr/share/glib-2.0/schemas
    sudo usermod -aG vboxusers david
fi