#!/bin/bash
# Personal setup script for my laptop computer
# ~Dragonwolf
# Version 1.0

if [[ $EUID -ne 0 ]]; then
   	echo "This script must be run as root type: sudo ./installscript" 
   	exit 1
else
	#Fetching Needed Files
		echo "Fetching needed files"
		cd /tmp
		wget  https://github.com/Dreamingwolf/Setup-Scripts/raw/master/sudoers_update
		wget  https://github.com/Dreamingwolf/Setup-Scripts/raw/master/Dragonwing_hosts

	#Updating Sudoers File to Add NOPASSWD to User
		echo "Adding NOPASSWD to sudoers file"
		sudo cat ./sudoers_update >> /etc/sudoers

	#Update hosts file
		echo "Updating the hosts file"
		sudo cat ./Dragonwing_hosts > /etc/hosts
		
fi
	