#!/bin/bash
# Personal setup script for my laptop computer
# ~Dragonwolf
# Version 2.1


	#Updating Sudoers File to Add NOPASSWD to User
        echo "Sudo password is required for certain commands in this script."
        echo "Entering an incorrect password will cause the script to crash."
        read -r -s -p "Enter password: " SUDOPWD && printf "\n"
        echo "$SUDOPWD" | sudo -S sh -c "echo \"$USER ALL=(ALL) NOPASSWD: ALL\" >&- > /etc/sudoers.d/90-$USER"

	#Fetching Needed Files
		echo "Fetching needed files"
		cd /tmp || return
		wget https://github.com/Dreamingwolf/Setup-Scripts/raw/master/arch_repos
		wget  https://github.com/Dreamingwolf/Setup-Scripts/raw/master/Dragonbone_hosts

	#Update hosts file
		echo "Updating the hosts file"
        sudo hostnamectl set-hostname Dragonbone
		sudo mv -f ./Dragonbone_hosts /etc/hosts
	
	#Update and Upgrade
    	echo "Updating and Upgrading"
        wget https://aur.archlinux.org/cgit/aur.git/snapshot/yay-bin.tar.gz
        sudo tar -xvf ./yay-bin.tar.gz
        cd yay-bin || return
        makepkg -i
        cd .. || return
        sudo rm -fR ./yay-bin
		cd /tmp || return
    	while read -r; do
            sudo tee -a /etc/pacman.conf
        done < "./arch_repos"
        sudo pacman-key --init
        sudo pacman-key --populate archlinux
        sudo pacman-key --recv-keys 932BA3FA0C86812A32D1F54DAB5964AEB9FEDDDC
        sudo pacman-key --lsign-key 932BA3FA0C86812A32D1F54DAB5964AEB9FEDDDC
        sudo pacman-key --recv-keys 313F5ABD
        sudo pacman-key --lsign-key 313F5ABD
        sudo pacman-key --recv-keys 4B4E7A9523ACD201
        sudo pacman-key --lsign-key 4B4E7A9523ACD201
        sudo pacman-key --recv-keys 7448C890582975CD 
        sudo pacman-key --lsign-key 7448C890582975CD
        curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
        sudo pacman -Sy reflector
    	sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist
    	sudo pacman -Syy
	    yay --editmenu --nodiffmenu --save

    # Overgrive prep
        yay -S --needed libnotify python python2-pyinotify python2-pip python2-gobject libappindicator-gtk3
        sudo pip2.7 install --upgrade google-api-python-client
        sudo pip2.7 install --upgrade oauth2client

    # Main Program install commands
        sudo pacman -Rn --cascade firefox chromium dropbox spotify vivaldi-codecs-ffmpeg-extra-bin vivaldi
	    yay -S --needed linux-headers pass ruby xorg-server-devel qrencode tk firefox-nightly thunderbird-nightly rawtherapee
	    yay -S --needed p7zip p7zip-gui wimlib overgrive qtwebflix-git zoom discord telegram-desktop-systemqt-notoemoji smplayer smplayer-themes smplayer-skins smtube youtube-dl mplayer
	    yay -S --needed python-pyqt5 drkonqi breeze-icons gst-libav flite kwalletmanager kio-extras kdoctools knetattach kirigami2 qt5-tools catdoc kdeconnect sdl_image sox movit
	    yay -S --needed dvdauthor dvgrab recordmydesktop simplescreenrecorder xine-ui xsane-gimp dvd+rw-tools vcdimager emovix cdrdao transcode openmp dmenu pam-gnupg-git luajit
	    yay -S --needed python-opengl qt5-xmlpatterns qt5-serialport qt5-websockets qt5-connectivity qt5-networkauth kimageformats khtml libappimage clang botan kde-cli-tools opusfile
	    yay -S --needed gnome-boxes libvirt virtualbox virtualbox-guest-dkms virtualbox-guest-iso virtualbox-guest-utils virtualbox-host-dkms sublime-text sublime-merge neofetch
	    yay -S --needed steam steam-fonts pidgin-opensteamworks linux-steam-integration sc-controller-git steamcurses-git proton-git python2-steamodd protonfixes-git gimp obs-studio
	    yay -S --needed lib32-mesa-vdpau lib32-libpulse lib32-jack lib32-libsamplerate lib32-speex lib32-giflib lib32-libldap lib32-gnutls lib32-mpg123 lib32-openal lib32-v4l-utils
	    yay -S --needed lib32-libxcomposite lib32-libxinerama opencl-icd-loader lib32-opencl-icd-loader lib32-libxslt lib32-gst-plugins-base-libs python2-pygments python2-rdflib
	    yay -S --needed lib32-sdl lib32-fluidsynth lib32-opencl-driver lutris hexchat shotwell audacity reaper-bin guvcview jdk-openjdk java-rhino catfish grub-customizer
	    yay -S --needed fusesmb samba cifs-utils exfat-utils ntfs-3g-fuse engrampa arj lzip unrar unace darktable gwenview inkscape okular skanlite hplip xsane xsane-gimp
	    yay -S --needed kipi-plugins kamera kdegraphics-mobipocket chmlib calligra libmediawiki libkvkontakte libwpg libwps libvisio libetonyek pstoedit openjpeg libgit2 curl
	    yay -S --needed openshot simplescreenrecorder libreoffice-fresh libmythes beanshell shellcheck unixodbc postgresql-libs coin-or-mp wqy-zenhei redshift numlockx variety
	    yay -S --needed gv ebtables bridge-utils radvd ceph qemu-block-gluster qemu-block-iscsi qemu-block-rbd qemu-arch-extra python2-pyquery python2-restkit terminator zsh
	    sudo glib-compile-schemas /usr/share/glib-2.0/schemas
	    sudo usermod -aG vboxusers david
	    sudo usermod -aG vboxfs david
    	yay -Syu

    #Add ssh key
        eval "$(ssh-agent -s)"
        ssh-add /home/david/.ssh/id_rsa

	#Cleanup
    	echo "Cleaning up"
    	sudo rm ./Dragonbone_hosts
    	sudo rm ./arch_repos

    	echo "DON'T FORGET TO REBOOT!"

	